src/main/scala/com/danielasfregola/twitter4s/http/unmarshalling/JsonSupport.scala
This resolves #5 issue - Response parser error No usable value for created_at
=> Using `Locale.ENGLISH` rather than the user default `Locale`

.travis.yml
this should avoid failures because of limited resources on travis
=> Running tests sequentially on travis

src/main/scala/com/danielasfregola/twitter4s/http/oauth/OAuth2Provider.scala, src/main/scala/com/danielasfregola/twitter4s/http/package.scala, src/main/scala/com/danielasfregola/twitter4s/util/UriHelpers.scala, src/test/scala/com/danielasfregola/twitter4s/helpers/RequestDSL.scala, src/test/scala/com/danielasfregola/twitter4s/helpers/Spec.scala, src/test/scala/com/danielasfregola/twitter4s/util/UriHelpersSpec.scala
Apparently, the definition of Uri.Authority.toString() has changed and this is breaking the library when overriding the version of `akka-http` from 10.0.1 to 10.0.3 (or higher).
I have changed the definition of `endpoint`, used when generating authentication tokens, to a safer approach.
=> #125 Conflict akka_http 10.0.3

src/main/scala/com/danielasfregola/twitter4s/http/oauth/OAuth2Provider.scala
The function searchTweet throws an error "Could not authenticate you code 32" when the query contains a space.
` val f = restClient.searchTweet(query="docker AND swarm",language = Some(Language.French)).map{
data => data.data.statuses.foreach{
t => println(t.text)
}
}
Await.result(f,Duration.Inf)
`
The problem comes from the signature: the parameter must be encoded one time for the uri and one more time for the signature.  
> Make sure to percent encode the parameter string! The signature base string should contain exactly 2 ampersand ‘&’ characters. The percent ‘%’ characters in the parameter string should be encoded as %25 in the signature base string.
[Creating the signature base string](https://dev.twitter.com/oauth/overview/creating-signatures)
I hope my PR helps you and thank you …
=> Parametter must be encoded twice for the signature

src/test/scala/com/danielasfregola/twitter4s/helpers/FixturesSupport.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClientSpec.scala
In order to make all tests pass even if the system's default character encoding is not UTF-8
=> Change tests to load all resources using UTF-8 character encoding

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala
Fix #131
Somehow [TwitterMediaClient.appendMediaChunk](https://github.com/DanielaSfregola/twitter4s/blob/a4a13a7649f8259a9510fa469fd6c5b9a2a64a4c/src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala#L119) is converted into `application/json` instead of `multipart/form-data` when post-ing due to custom unmarshaller related to the following akka-http [issue](https://github.com/akka/akka-http/issues/541) and akka-http-json [issue](https://github.com/hseeberger/akka-http-json/issues/148)
So, I just removed the implicit native serialization from `JsonSupport` and put it in scope where it is needed and it seems to work.
I would be glad if you had a better suggestion to solve the issue. Thanks!
=> Fix error when uploading media due to custom unmarshaller

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
Remove `new` modifier when instantiating `TwitterStream` since its a case class
=> Minor improvement in StreamingClient

src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/DisconnectMessage.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/LimitNotice.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/LocationDeletionNotice.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/StatusDeletionNotice.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/StatusWithheldNotice.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/UserWithheldNotice.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/common/WarningMessage.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/site/ControlMessage.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/site/UserEnvelop.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/user/Event.scala, src/main/scala/com/danielasfregola/twitter4s/entities/streaming/user/FriendsLists.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/friends/TwitterFriendClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/friendships/TwitterFriendshipClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
I noticed the work on #149 and noticed that while most of the links are fixed there are still some left. Most of them are actually being redirected to the right page, but others are being redirected to a generic streaming tutorial. I started fixing the ones left pointing to `dev.*`  but wanted to get some feedback before going further.
Do you want to fix all links to `dev.*` and replace them with the appropriate link to `developer.*`?
=> Fix links to twitter docs

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/account/TwitterAccountClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/favorites/TwitterFavoriteClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/followers/TwitterFollowerClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/friends/TwitterFriendClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/lists/TwitterListClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
This should fix almost all of the documentation links for #149 
I wasn’t able to find proper links for these two instances:
1. `http/clients/streaming/statuses/TwitterStatusClient.scala` is linking to `https://dev.twitter.com/streaming/reference/get/statuses/firehose` which returns a 404
2. `entities/streaming/site/ControlMessage.scala` is linking to  `https://dev.twitter.com/streaming/sitestreams/controlstreams` which redirects to something very generic.
Both instances I couldn’t find in the [API reference index — Twitter      Developers](https://developer.twitter.com/en/docs/api-reference-index) for that matter.
If you need me to rebase these commits in some form, let me know.
=> Fix links to twitter docs (part deux)

src/main/scala/com/danielasfregola/twitter4s/entities/enums/FilterLevel.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusFilters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusSampleParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/parameters/UserParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoder.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClientSpec.scala
This PR :
- Partially addresses #71. Reference: [Basic stream parameters](https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters)
As I don't have access to both of these stream endpoints, Im not confident to modify it since I can't do the UAT.
Plus I can't find the documentation for this two endpoints.
FYI, User streams and Site streams will be deprecated some time in the future. See [here](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview).
- Fix #130
I don't think we should mention `comma-separated` in the docs since that is basically hidden behind the API. 
Also, I removed most of the links which are not active anymore.
- Fix locations parameters
It needs to be a list of longitude,latitude pairs. I added …
=> Support all standard params for filter, sample statuses and user events

src/main/scala/com/danielasfregola/twitter4s/entities/Coordinate.scala, src/main/scala/com/danielasfregola/twitter4s/entities/GeoBoundingBox.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusFilters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/parameters/UserParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoder.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoderSpec.scala
Fixes #169.
Refer to location model from [twitter-hbc](https://github.com/twitter/hbc/blob/master/hbc-core/src/main/java/com/twitter/hbc/core/endpoint/Location.java).
I find the name `Location` a bit ambiguous. So, I followed [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html) API, and name it `GeoBoundingBox`.
Also, from twitter docs, the documentation for locations are: A comma-separated list of longitude,latitude pairs specifying a set of bounding boxes to filter Tweets by.
=> Fix location filter parameters for streaming client

.travis.yml
As suggested in #177 , we should build for both JDK 7 and JDK 8
=> Trying to build using JDK 7

src/main/scala/com/danielasfregola/twitter4s/entities/Media.scala, src/main/scala/com/danielasfregola/twitter4s/entities/Variant.scala, src/main/scala/com/danielasfregola/twitter4s/entities/VideoInfo.scala, src/test/resources/fixtures/rest/favorites/favorites.json, src/test/resources/fixtures/rest/statuses/home_timeline.json, src/test/resources/fixtures/rest/statuses/retweets.json, src/test/resources/fixtures/rest/statuses/retweets_of_me.json, src/test/resources/fixtures/rest/statuses/show.json, src/test/resources/fixtures/rest/statuses/user_timeline.json, src/test/resources/fixtures/streaming/site/user_envelop_tweet_event.json, src/test/resources/fixtures/streaming/site/user_envelop_tweet_event_stringified.json, src/test/resources/fixtures/streaming/user/events.json, src/test/resources/twitter/rest/statuses/home_timeline.json
Created class for VideoInfo, Variant and included attribute in the Media for issue #181. Fixtures files updated to support the new field and one new json included in home_timeline.json to test the new parser.
This PR is based in the tag v5.2.
=> VideoInfo support

build.sbt, src/main/scala/com/danielasfregola/twitter4s/entities/LocationTrends.scala, src/test/resources/fixtures/rest/trends/trends.json, src/test/resources/twitter/rest/trends/trends.json
Twitter is providing twitter_volume field as part of the response when getting Trends by Location
See: https://developer.twitter.com/en/docs/trends/trends-for-location/api-reference/get-trends-place
I just have added the field to the Trends object to be parsed from the response.
=> Add twitter_volume as a field to be get by Trends by Location endpoint

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/ErrorHandler.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala, src/test/scala/com/danielasfregola/twitter4s/helpers/ClientSpec.scala
part of https://github.com/DanielaSfregola/twitter4s/issues/144
=> add custom error handler

src/main/scala/com/danielasfregola/twitter4s/TwitterRestClient.scala
Following on from https://github.com/DanielaSfregola/twitter4s/issues/237#issuecomment-474426923 this is the smallest change required to get the constructor-overriding hack in this gist to work:
https://gist.github.com/rtyley/dc341992a6104f4b499834fd2d10dfad
=> Make TwitterRestClient constructor accessible to allow app-only-auth hack

build.sbt, src/main/scala/com/danielasfregola/twitter4s/http/clients/OAuthClient.scala, src/test/scala/com/danielasfregola/twitter4s/helpers/Spec.scala, src/test/scala/com/danielasfregola/twitter4s/http/oauth/OAuth1ProviderSpec.scala
I tried using twitter4s with latest akka and akka-http but twitter4s kept failing with the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: akka.http.scaladsl.model.MediaTypes$.application$divx$minuswww$minusform$minusurlencoded()Lakka/http/scaladsl/model/MediaType$WithOpenCharset;
at com.danielasfregola.twitter4s.http.clients.OAuthClient$OAuthRequestBuilder.apply(OAuthClient.scala:47)
at com.danielasfregola.twitter4s.http.clients.streaming.statuses.TwitterStatusClient.filterStatuses(TwitterStatusClient.scala:64)
at com.danielasfregola.twitter4s.http.clients.streaming.statuses.TwitterStatusClient.filterStatuses$(TwitterStatusClient.scala:51)
at com.danielasfregola.twitter4s.TwitterStreamingClient.filterStatuses(TwitterStreamingClient.scala:14)
```
akka-http has …
=> Bump akka and akka-http version to latest version

.travis.yml, build.sbt, project/plugins.sbt, src/main/scala/com/danielasfregola/twitter4s/http/clients/Client.scala, src/main/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoder.scala, src/main/scala/com/danielasfregola/twitter4s/http/oauth/OAuth1Provider.scala, src/main/scala/com/danielasfregola/twitter4s/http/serializers/StreamingMessageFormats.scala
This PR updates `twitter4s` to compile with Scala 2.13 by default, while still cross-compiling to Scala 2.12 & 2.11.
Although Scala 2.13.**1** has been released, this change sticks with 2.13.**0**, as `scoverage` has not yet released an update compatible with that latest version (see scoverage/sbt-scoverage#295, scoverage/sbt-scoverage#299) -  the current latest release of `scoverage`, 1.6.0, only works with  Scala 2.13.0.
Migration issues addressed with this update:
* Underscore (`_`) is no longer a valid identifer for `val`s
* `Map.mapValues()` now returns a `MapView` rather than a `Map`
* `.to` can no longer infer what resulting collection type you want
=> Add Scala 2.13 support

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClient.scala
The deprecation warning mentioned a method "messageCreate" that was renamed to createDirectMessageEvent
As this is misleading (I searched for that method during 20 minutes), I fixed the documentation to match the correct method name
=> Update deprecation in TwitterDirectMessageClient

src/main/scala/com/danielasfregola/twitter4s/entities/MediaDetails.scala
Makes a few media upload/status fields optional since they sometimes aren't returned by twitter.
=> Make some media upload/status fields optional

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/parameters/MediaInitParameters.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClientSpec.scala
Adds support for the `media_category` field on chunked uploads, which allows
* Up to 15 MB animated GIFs to be uploaded 
* Up to 512 MB videos to be uploaded (according to documentation; I verified I could upload a 42 MB and not the 512 MB limit, so this assumes twitter documentation is accurate)
* Videos to be uploaded longer than 30 seconds (not specifying `media_category: 'tweet_video'` and uploading a long video gives an error saying the max duration is 30 seconds)
* Images
* Verified 4 mb image (1 chunk)
* Failed to upload 7.8 mb image (expected; documented limit is 5 mb)
* GIF
* Verified 4.7 mb gif (1 chunk)
* Verified 6.6 mb gif (2 chunks)
* Video
* Verified 1 mb video (1 chunk)
* Verified 10.9 mb video (3 chunks)
* Verified 42 mb video (9 chunks)
=> Support media_category for chunked media uploads

src/main/scala/com/danielasfregola/twitter4s/entities/TweetSearch.scala
Twitter does not include the `refresh_url` when searching popular tweets. 
The search metadata for `https://api.twitter.com/1.1/search/tweets.json?q=lang:en&count=100&result_type=popular` looks as follows:
```json
"search_metadata": {
"completed_in": 0.045,
"max_id": 0,
"max_id_str": "0",
"next_results": "?max_id=1275972098247270401&q=lang%3Aen&count=100&include_entities=1&result_type=popular",
"query": "lang%3Aen",
"count": 100,
"since_id": 0,
"since_id_str": "0"
}
```
My proposed solution is to make the refresh_url optional. This mitigates deserialization errors.
=> Fix absent refresh_url on popular result_type search

src/main/scala/com/danielasfregola/twitter4s/entities/MediaDetails.scala
I discovered that this field wasn't returned when `state == "pending"` so `processing_info` wouldn't get deserialized. I did not make `state` optional since the twitter docs seem to indicate that if `processing_info` exists, then so does `state`, but I could be convinced to make it optional anyways.
=> Make `progress_percent` optional

src/main/scala/com/danielasfregola/twitter4s/TwitterRestV2Client.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/Includes.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/TweetIncludes.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/User.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/UserEntities.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/UserIncludes.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/UserExpansions.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/responses/TweetResponse.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/responses/TweetsResponse.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/responses/UserResponse.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/responses/UsersResponse.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/TwitterUserLookupClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UserByUsernameParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UserParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UsersByUsernamesParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UsersParameters.scala, src/test/resources/twitter/rest/v2/users/userlookup/user.json, src/test/resources/twitter/rest/v2/users/userlookup/users.json, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/TweetResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/TweetsResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/TwitterUserLookupClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/fixtures/UserResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/fixtures/UsersResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/utils/V2SpecQueryHelper.scala
This PR adds full support for the [User Lookup](https://developer.twitter.com/en/docs/twitter-api/users/lookup/introduction) endpoints under Twitter's new V2 API. 
The user based endpoints are being built with Tweet materialization permitted. Likewise, with the addition of this user model, the Tweet endpoints can be updated to permit User materialization. However, to cut down on PR complexity, these changes will be included in a separate PR.
=> Create V2UserLookupClient with User fields

src/main/scala/com/danielasfregola/twitter4s/entities/v2/TweetIncludes.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/TweetExpansions.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClient.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/TweetResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/TweetsResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/utils/V2SpecQueryHelper.scala
A short and sweet pr which allows for user fields to be queried by the tweet lookup endpoints.
=> User Fields available on Tweet Lookup

src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/TweetExpansions.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/UserExpansions.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTimelinesClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/paramaters/TimelineMentionsParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/paramaters/TimelineTweetsParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/paramaters/TweetParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/paramaters/TweetsParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/TwitterUserLookupClient.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UserByUsernameParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UserParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UsersByUsernamesParameters.scala, src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/parameters/UsersParameters.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTimelinesClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/users/TwitterUserLookupClientSpec.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/utils/V2SpecQueryHelper.scala
👋 Another PR here to rename `TweetExpansions.Expansions` and `UserExpansions.Expansions` to match their parent object.
This naming mistake was made earlier on and creates situations where the import needs to be renamed as to not conflict with its counterpart.
=> Explicitly name Tweet and User expansions

src/main/scala/com/danielasfregola/twitter4s/entities/v2/Media.scala, src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/MediaType.scala, src/main/scala/com/danielasfregola/twitter4s/http/serializers/EnumFormats.scala, src/test/resources/twitter/rest/v2/tweets/tweet.json, src/test/resources/twitter/rest/v2/tweets/tweets.json, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/deserialization/fixtures/TweetResponseFixture.scala, src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/deserialization/fixtures/TweetsResponseFixture.scala
[Media.type documentation](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media) states that this field can only be one of `animated_gif`,`photo`, and `video`. So we can better represent this field with an enum.
=> Add MediaType enum

src/main/scala/com/danielasfregola/twitter4s/TwitterRestV2Client.scala
A correction for a bad copy job. The `apply` methods for TwitterRestV2Client should return V2 instances.
=> Apply method for TwitterRestV2Client return V2

src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/TweetReplySetting.scala
While not documented on [Twitter's Object Model](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet), "following" is a new value being returned by `reply_settings`.
[*IDs and names obfuscated*] 
```
{
"id": "1445555554710916097",
"reply_settings": "everyone",
"text": "@WhereWhereJoeJoes We're so happy to have you as a member of our community 🥰"
},
{
"id": "144555555545356289",
"reply_settings": "following", <==== New?
"text": "@mooretyyy We love it 😍"
},
{
"id": "1455555555229575682",
"reply_settings": "everyone",
"text": "@cdgelodge @caracaradd Shout out to the mountain for being a sponsor 😂⛰️❤️"
},
```
=> Add "following" TweetReplySetting enum

README.md
Hello! As a new user, I struggled for quite a while debugging dependencies before finding out that Twitter has deprecated V1.X endpoints for new users at the default access level. See https://twittercommunity.com/t/ushering-in-a-new-era-for-the-twitter-developer-platform-with-the-twitter-api-v2/162087
Maybe we can add in an error message later. But for now, let's update the README.
=> Update README with access requirements
