DanielaSfregola/twitter4s

src/main/scala/com/danielasfregola/twitter4s/entities/enums/MediaType.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/media/TwitterMediaClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/media/parameters/MediaInitParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/media/parameters/MediaMetadataCreation.scala
src/main/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoder.scala
src/test/resources/fixtures/media/media_details.json
src/test/resources/twitter/media/media_details.json
src/test/scala/com/danielasfregola/twitter4s/http/clients/account/TwitterAccountClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/lists/TwitterListClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/media/TwitterMediaClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/statuses/TwitterStatusClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoderSpec.scala

#6 media support tests and documentation

---

README.md
project/Twitter4s.scala

Release 0.2 with README

---

src/main/scala/com/danielasfregola/twitter4s/TwitterClient.scala
src/main/scala/com/danielasfregola/twitter4s/entities/AccessToken.scala
src/main/scala/com/danielasfregola/twitter4s/entities/ConsumerToken.scala
src/main/scala/com/danielasfregola/twitter4s/util/Configurations.scala

#11 Now detecting config from env variables

---

src/main/scala/com/danielasfregola/twitter4s/util/Configurations.scala

#11 Improved env variable detection error message

---

src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/entities/DirectMessage.scala
src/main/scala/com/danielasfregola/twitter4s/entities/enums/WithFilter.scala
src/main/scala/com/danielasfregola/twitter4s/entities/streaming/FriendsLists.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/StreamingOAuthClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/parameters/UserParameters.scala
src/main/scala/com/danielasfregola/twitter4s/processors/TwitterProcessor.scala
src/main/scala/com/danielasfregola/twitter4s/util/Configurations.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClientSpec.scala

#15 added support for user streams

---

src/main/resources/reference.conf
src/main/scala/com/danielasfregola/twitter4s/TwitterRestClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/util/Configurations.scala

#25 making twitter domain configurable

---

0.2.1-README.md
README.md
build.sbt
project/Twitter4s.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/Client.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/processors/TwitterProcessor.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStreamingSpecContext.scala

#12 readme for 1.0

---

src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala

#38 Initialization of the clients is now consistent

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala

#40 Fixed documentation for get tweet

---

README.md

Fixed a small confusing typo (resolver -> resolvers) per http://www.scala-sbt.org/0.13/docs/Library-Dependencies.html#Resolvers
:D

Fix typo in Update.md

---

src/main/scala/com/danielasfregola/twitter4s/entities/Tweet.scala
src/test/resources/fixtures/rest/search/tweets.json

This PR contains a fix for a test broken following #52 .

#52 edit coordinates type to be able to get coordinates from client

---

README.md

#56 Updated README with contributor instructions

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusFilterParameters.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala

language filter has been added.
my test code is available here:
https://github.com/lachatak/tweetsampler/tree/twitter4s
there are couple of things still missing so it is not merged to master.
I need 'replace' and 'shutdown' function before the demo can be merged to master and deployed to heroku for demonstration purpose.

Filter by language #66

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/parameters/SiteParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusFirehoseParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/parameters/StatusSampleParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/parameters/UserParameters.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClientSpec.scala

This resolves #66 
Also, it completes #70 by applying the same change to all the streaming endpoints.

#66 Added language filter support to all streaming endpoints

---

.travis.yml
build.sbt
project/plugins.sbt
src/test/resources/application.conf
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/oauth/OAuth2ProviderSpec.scala
src/test/scala/com/danielasfregola/twitter4s/util/Spec.scala
src/test/scala/com/danielasfregola/twitter4s/util/TestExecutionContext.scala
src/test/scala/com/danielasfregola/twitter4s/util/rest/ClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/util/streaming/ClientSpec.scala

#54 Added Scala 2.12 support

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/StreamingClient.scala

this resolves an issue highlighted in question #82

#82 Fix for EntityStreamSizeException when using streaming client

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStream.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala

#67 Now we can refresh a stream

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient.scala

#84 Fixed documentation for searchTweets

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/CommonClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/package.scala
src/main/scala/com/danielasfregola/twitter4s/util/ActorContextExtractor.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClientSpec.scala

#91 Fixed search tweet query encoding

---

README.md
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStream.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStreamSpec.scala

#85 Improved documentation on stream close and replace

---

README.md
src/main/scala/com/danielasfregola/twitter4s/TwitterRestClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/test/resources/application.conf
src/test/scala/com/danielasfregola/twitter4s/TwitterRestClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/TwitterStreamingClientSpec.scala

This resolves and #104 and #103

#104 more apply and #103 close function

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/OAuthClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/account/TwitterAccountClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/application/TwitterApplicationClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/blocks/TwitterBlockClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/favorites/TwitterFavoriteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/followers/TwitterFollowerClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/friends/TwitterFriendClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/friendships/TwitterFriendshipClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/geo/TwitterGeoClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/help/TwitterHelpClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/lists/TwitterListClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/savedsearches/TwitterSavedSearchClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/suggestions/TwitterSuggestionClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/trends/TwitterTrendClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/sites/TwitterSiteClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/oauth/OAuth2Provider.scala

#112 Removed deprecated functions

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala

#118 Terminating actor system also in case of failures

---

README.md

....last ticket before releasing 5.0!

#114 Updated README with latest info on initialisation and rate information

---

src/main/scala/com/danielasfregola/twitter4s/http/package.scala

This closes #134 as this is a continuation of that PR

#134 fixed encoding for query search tweet

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/blocks/TwitterBlockClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClient.scala

 fixed links 4 Block and DM

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/mutes/TwitterMuteClient.scala

Updating 10 links on TwitterMuteClient

Updating links on TwitterMuteClient

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/application/TwitterApplicationClient.scala

Updated the developer.twitter.com link.

Updated TwitterApplicationClient

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/savedsearches/TwitterSavedSearchClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient.scala

Updated the links in the documentation of both files.

Updated TwitterSavedSearchClient and TwitterSearchClient

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/geo/TwitterGeoClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/help/TwitterHelpClient.scala

Fixed links for TwitterOAuthClient, TwitterGeoClient and TwitterHelpClient

#149 Fixed links TwitterOAuthClient, TwitterGeoClient and TwitterHelpClient

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClient.scala

Apparently, lots of information from the streaming clients is gone or at least I couldn't find it

#149 Updated links for streaming clients

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/suggestions/TwitterSuggestionClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/trends/TwitterTrendClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/users/TwitterUserClient.scala

- TwitterStatusClient
- TwitterSuggestionClient
- TwitterUserClient
- TwitterTrendClient

#149 Several links updates

---

README.md

This PR adds documentation in README to start a new project using Giter8 template for `twitter4s`
---
PR from Lambda World 2017 Scala Center Spree 😄

Add Giter8 template usage in README

---

README.md
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/CommonClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStream.scala
src/main/scala/com/danielasfregola/twitter4s/util/Logger.scala

I hope this is what was expected from #138: I changed all logging occurrences to logger scala-logging and updated the README.
Let me know if more is needed on this.

All logging uses now scala-logging, updated README

---

src/test/resources/fixtures/rest/media/img_media_details.json
src/test/scala/com/danielasfregola/twitter4s/helpers/RequestDSL.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClientSpec.scala

- Address #107 
- Add the ability to expect/response to multiple requests in RequestDSL.

Add test for media upload

---

.travis.yml
README.md
build.sbt
project/build.properties
project/doge.sbt
project/plugins.sbt
src/main/scala/com/danielasfregola/twitter4s/http/clients/authentication/AuthenticationClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/authentication/oauth/TwitterOAuthClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala
src/main/scala/com/danielasfregola/twitter4s/util/MediaReader.scala
src/test/scala/com/danielasfregola/twitter4s/helpers/JsonDiffSupport.scala

- Removed wrong java7 compatibility (on travis oraclejdk7 use java8 and with openjdk7 the build fails)
- Deps Updated
Needs to check if ScalaDoc is still working correctly with Sbt 1.0.4

Dependency Updates

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/lists/TwitterListClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/search/TwitterSearchClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/users/TwitterUserClient.scala
src/test/scala/com/danielasfregola/twitter4s/helpers/ClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/helpers/RequestDSL.scala

#197 Making sure killSwitch not returned before connection response

---

src/main/scala/com/danielasfregola/twitter4s/entities/LookupMapped.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClientSpec.scala

Replace LookupTweet by Tweet

---

src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/parameters/LookupParameters.scala
src/test/resources/fixtures/rest/statuses/lookup_extended.json
src/test/resources/fixtures/rest/statuses/lookup_mapped_extended.json
src/test/resources/twitter/rest/statuses/lookup_extended.json
src/test/resources/twitter/rest/statuses/lookup_mapped_extended.json
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/TwitterStatusClientSpec.scala

Add tweet_mode parameter to statuses/lookup

---

src/test/scala/com/danielasfregola/twitter4s/http/clients/streaming/statuses/TwitterStatusClientSpec.scala

#188 Making sure encoding for sequences work as expected

---

src/main/scala/com/danielasfregola/twitter4s/TwitterAuthenticationClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterRestClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/authentication/AuthenticationClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/RestClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/StreamingClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/streaming/TwitterStream.scala
src/main/scala/com/danielasfregola/twitter4s/util/SystemShutdown.scala

#185 Using external actor system

---

src/test/scala/com/danielasfregola/twitter4s/helpers/TestActorSystem.scala

#191 Fixed threads explosion in tests

---

src/main/scala/com/danielasfregola/twitter4s/TwitterAuthenticationClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterRestClient.scala
src/main/scala/com/danielasfregola/twitter4s/TwitterStreamingClient.scala

#207 Forcing to use apply to create clients

---

src/main/scala/com/danielasfregola/twitter4s/http/marshalling/BodyEncoder.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/parameters/LookupParametersSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/parameters/OEmbedParametersSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/statuses/parameters/RetweetersIdsParametersSpec.scala

Primarily: Fix #190
Also: Fix #214: Replaced Cons and Nil pattern with Seq to allow pattern matching on non-List Seq's.

Added dedicated tests for query parameters

---

src/main/scala/com/danielasfregola/twitter4s/entities/DirectMessageEvent.scala
src/main/scala/com/danielasfregola/twitter4s/entities/NewDirectMessageEvent.scala
src/main/scala/com/danielasfregola/twitter4s/entities/enums/TweetType.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/OAuthClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/parameters/CreateEventParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/parameters/ShowParameters.scala
src/main/scala/com/danielasfregola/twitter4s/http/serializers/CustomFormats.scala
src/main/scala/com/danielasfregola/twitter4s/http/serializers/EnumFormats.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/directmessages/TwitterDirectMessageClientSpec.scala

#229 Minor changes and clean up

---

src/main/scala/com/danielasfregola/twitter4s/http/serializers/CustomFormats.scala
src/main/scala/com/danielasfregola/twitter4s/http/serializers/JsonSupport.scala

I believe this caused #236: we were unable to parse Instant from long and int

#236 Fixed rate information parsing

---

src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/media/TwitterMediaClientSpec.scala

....unfortunately CI wasn't running as expected (my bad!) - the reason why this wasn't detected in the PR.

Fixed broken test introduced by #320

---

src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/fields/PlaceFields.scala

Resolve typo in PlaceFields enum

Resolve typo in PlaceFields enum

---

src/main/scala/com/danielasfregola/twitter4s/entities/v2/Media.scala
src/main/scala/com/danielasfregola/twitter4s/entities/v2/TweetIncludes.scala
src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/TweetExpansions.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTimelinesClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClient.scala
src/test/resources/twitter/rest/v2/tweets/timelines/tweets.json
src/test/resources/twitter/rest/v2/tweets/tweetlookup/tweet.json
src/test/resources/twitter/rest/v2/tweets/tweetlookup/tweets.json
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTimelinesClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClientSpec.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/timelines/TweetsResponseFixture.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/tweet_lookup/TweetResponseFixture.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/fixtures/tweet_lookup/TweetsResponseFixture.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/utils/V2SpecQueryHelper.scala

Implement the media model and add a few tests for it. Fixtures and test data have been updated to reflect the full range of potential response fields for media.

Add the Media model

---

src/main/scala/com/danielasfregola/twitter4s/entities/v2/Place.scala
src/main/scala/com/danielasfregola/twitter4s/entities/v2/Poll.scala
src/main/scala/com/danielasfregola/twitter4s/entities/v2/TweetIncludes.scala
src/main/scala/com/danielasfregola/twitter4s/entities/v2/enums/expansions/TweetExpansions.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterSearchTweetsClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTimelinesClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/TwitterTweetLookupClient.scala
src/main/scala/com/danielasfregola/twitter4s/http/serializers/CustomFormats.scala
src/test/resources/twitter/rest/v2/tweets/tweet.json
src/test/resources/twitter/rest/v2/tweets/tweets.json
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/deserialization/fixtures/TweetResponseFixture.scala
src/test/scala/com/danielasfregola/twitter4s/http/clients/rest/v2/tweets/deserialization/fixtures/TweetsResponseFixture.scala

Adds materialization support for the `Place` and `Poll` fields.

Add Place and Poll support
